### ISSUE TITLE
Unneccessary logging when processing timestamps

### ISSUE THREAD

**Issue by algestam** [mikebski/logstash-filter-datepart#3]
When using the datepart filter together with logstash 5.0.0-beta1 I have noticed that the logstash log is full of entries like this:

    [2016-09-26T08:49:07,159][INFO ][logstash.filters.dateparts] Class is LogStash::Timestamp

The issue is not critical but a bit annoying and may have a negative effect on performance. I would prefer to either change the loglevel for this statement to debug or add another clause in the code that skips this log statement for `LogStash::Timestamp` (like what is currently implemented for `Time`).

**Comment by mikebski** [comment]
This should have been removed, I don't think it is useful even for debug.  I will create a patch for this.

Thanks.

**Comment by algestam** [comment]
Thanks!
